# Generated by Django 5.2.13 on 2026-05-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='file_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='project_assets/'),
        ),
    ]
